# -*- coding: utf-8 -*-
"""app lulus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQRggGTe18ZXalgRDe4zy9_jrxCa90q6
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load('best_model.pkl')

st.title("🎓 Prediksi Kelulusan Tepat Waktu")

st.sidebar.header("Masukkan Data")

# Fungsi input manual
def input_user():
    ipk = st.sidebar.number_input("IPK", min_value=0.0, max_value=4.0, value=3.0)
    pelatihan = st.sidebar.number_input("Pelatihan Pengembangan Diri", min_value=0, value=1)
    prestasi = st.sidebar.number_input("Prestasi", min_value=0, value=0)
    forum = st.sidebar.number_input("Forum Komunikasi Kuliah", min_value=0, value=1)
    organisasi = st.sidebar.number_input("Kegiatan Organisasi", min_value=0, value=0)

    data = {
        'IPK': [ipk],
        'Pelatihan Pengembangan Diri': [pelatihan],
        'Prestasi': [prestasi],
        'Forum Komunikasi Kuliah': [forum],
        'Kegiatan Organisasi': [organisasi]
    }
    return pd.DataFrame(data)

# Pilihan mode input
input_mode = st.radio("Pilih mode input", ["Manual", "Upload CSV"])

if input_mode == "Manual":
    input_df = input_user()
else:
    uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])
    if uploaded_file is not None:
        input_df = pd.read_csv(uploaded_file)
        # Validasi kolom
        expected_cols = ['IPK', 'Pelatihan Pengembangan Diri', 'Prestasi', 'Forum Komunikasi Kuliah', 'Kegiatan Organisasi']
        if not all(col in input_df.columns for col in expected_cols):
            st.error(f"Kolom CSV harus: {', '.join(expected_cols)}")
            st.stop()
    else:
        st.warning("Silakan upload file CSV.")
        st.stop()

# Tampilkan data input
st.write("### Data yang Dimasukkan:")
st.write(input_df)

# Prediksi
if st.button("Prediksi"):
    predictions = model.predict(input_df)

    # Mapping 0/1 ke teks sederhana
    label_map = {0: "Tidak Lulus Tepat Waktu", 1: "Lulus Tepat Waktu"}
    pred_labels = [label_map[p] for p in predictions]

    input_df['Hasil Prediksi'] = pred_labels

    st.write("### Hasil Prediksi:")
    st.write(input_df[['Hasil Prediksi']])

    # Jika hanya satu data, tampilkan teks besar
    if len(input_df) == 1:
        st.success(f"Hasil: **{pred_labels[0]}**")